const CREATE = 0;
const EDIT = 1;
const VIEW = 2;
const READONLY = 3;

const FORM_MODE = {
  CREATE: CREATE,
  EDIT: EDIT,
  VIEW: VIEW,
  READONLY: READONLY,
};

const PART_STATE = {
  OK: 1,
  DAMAGED: 2,
  MISSING: 3,
};

const STORAGE_TYPE = {
  CART: 0,
  RACK: 1,
};

const CART_TYPE = {
  ANY: 0,
  FACE_FRAME_PARTS: 1,
  MULTI_5_PIECE_FRONTS_PARTS: 2,
  DRAWER_BOX_PARTS: 3,
};

const CART_STATUS = {
  DISABLED: 0,
  ACTIVE: 1,
};

const FILTERS = {
  ALL_PARTS: 0,
  CARCASS_PARTS: 1,
  CARCASS_PARTS_NEW: 12,
  CARCASS_PARTS_CHILDS: 10,
  DRAWER_BOX_PARTS: 2,
  DOOR_DRAWER_FRONTS_PARENTS: 11,
  DOOR_DRAWER_FRONTS_SINGLE: 3,
  FACE_FRAME_PARTS: 4,
  CARCASS_NOP_MULTI_AND_DRAWER_BOX_MULTI: 5,
  CARCASS_NOP_MULTI_AND_DRAWER_BOX_SINGLE: 6,
  ART_ID: 13,
  TOE_KICK: 7,
  MULTI_5_PIECE_FRONTS_PARTS: 8,
  MULTI_PARTS: 9,
};

const PART_TYPES = {
  CARCASS_PARTS: [14, 5, 4, 1, 13, 6, 12, 3, 34],
  CARCASS_PARTS_NEW: [14, 5, 4, 1, 13, 6, 12, 34, 8, 23, 9, 10],
  CARCASS_PARTS_CHILDS: [14, 5, 4, 1, 13, 6, 12, 3, 34],
  DRAWER_BOX_PARTS: [21, 22],
  DOOR_DRAWER_FRONTS_PARENTS: [23, 8, 9, 10],
  DOOR_DRAWER_FRONTS_SINGLE: [23, 8, 9, 10],
  FACE_FRAME_PARTS: [36],
  CARCASS_NOP_MULTI_AND_DRAWER_BOX_MULTI: [
    14, 5, 4, 1, 13, 6, 12, 3, 34, 21, 22,
  ],
  get CARCASS_NOP_MULTI_AND_DRAWER_BOX_SINGLE() {
    return [
      ...PART_TYPES.CARCASS_NOP_MULTI_AND_DRAWER_BOX_MULTI,
      ...PART_TYPES.DOOR_DRAWER_FRONTS_SINGLE,
    ];
  },
  ART_ID: [1],
  TOE_KICK: [27],
  MULTI_5_PIECE_FRONTS_PARTS: [8, 9, 10, 23],
  MULTI_PARTS_EXCLUDE: [8, 9, 10, 23, 27],
};

export default {
  FORM_MODE,
  PART_STATE,
  STORAGE_TYPE,
  CART_TYPE,
  FILTERS,
  CART_STATUS,
  PART_TYPES,
};
